# Generated by Django 3.2 on 2022-09-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220915_0906'),
        ('user', '0003_alter_user_table'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='stock',
            field=models.ForeignKey(db_column='stock', on_delete=django.db.models.deletion.PROTECT, to='stock.stock'),
        ),
    ]
