# Generated by Django 3.2 on 2022-11-04 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_table'),
        ('product', '0003_auto_20220915_0906'),
        ('sale', '0002_alter_sale_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
    ]
