# Generated by Django 3.2 on 2022-09-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_user_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_user_name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
